### ISSUE TITLE
Personlig Process Logbog

### ISSUE THREAD

**Issue by Emythiel** [ITA-Super-Cool-Pals/StableStable#21]
Log process ned i kommentarende her

**Comment by SushiGirrl** [comment]
* User research (well documented)
* Dobbelt diamnod model
* CanBan (GitHub project manager)
* lavet en mere skarp prioritering af vigtigste features
* MVP_01(misforstået lidt, lidt rushed)
* MVP_02 (skal testes hurtigsts muligt)
* problemer med arkitektur
* implementerer coroutines i vores repositories til databasen, for at undgå async og callback hell
* undgå hashmaps, bruge data class object with as lists instead
* holde navController i navigation og isteddet skrive functioner til routes i navigation
* Føre logbog via "Issues"

**Comment by Josef-TL** [comment]
Coroutines er blevet implementeret. Det giver lidt mere frihed, da vi ikke behøves at bruge callback functions mere.

Vi burde nok finde en løsning til lang loading tid.

**Comment by SushiGirrl** [comment]
Inspired by Geeks for Geeks video tutorial about push notifications:
https://www.youtube.com/watch?v=2xoJi-ZHmNI

**Comment by Emythiel** [comment]
Kalender ting til at vælge en hests fødselsdag var lidt af en pain, især at skulle få den vist.
.clickable til OutlinedTextField er genialt, det putter en clickable box *bag* text field, så man kan ikke trykke på den.

Men den er "done" ish for nu.

**Comment by Josef-TL** [comment]
Har bygget starten på vores vagtplan. Man kan nu klikke på en boks og der dukker en dialog op, som man lige nu kun kan lukke.

Lige nu struggler jeg lidt med størrelsen på ting, fx er boksen man kan klikke på ikke fyldt ud til den container.

Havde en diskussion med Lykke om vores home screen, tilbage-knap vs home-knap; Lykke mener end-goal skal være at have de knapper vi lige nu har på home screen, på en navigation bar. I det tilfælde giver det mening ikke at have en tilbage-knap/home-knap.

Har oprettet et Issue omkring dette: hvis vi skal have en nav-bar skal vi nok implementere den snarest muligt.

**Comment by SushiGirrl** [comment]
VSC conflict resolving
- Hard reset locally to earlier commit
- Pushing resulted in conflict
- Tried Merge, but I wanted to keep my current local version and NOT merge it with the remote version
- Solved it by simply deleting the things I did not want in my branch
CONCLUSION
I could have just done this from the beginning and not reset my branch

**Comment by Emythiel** [comment]
Basisk tilføjelse af heste til database done.

Rettet noget userprofile data ting, så vi ikke hele tiden behøver at fetche det - det bliver gemt i authviewmodel når man logger ind / er logget ind

**Comment by SushiGirrl** [comment]
Rapport:
Hvad ville vi gøre hvis vi havde mere tid?

* lave nested navigation (smart for scaffolds til grupper af screens og popback-stack)

**Comment by Emythiel** [comment]
Lod min Mor bruge appen, og prøve den lidt, for at få feedback.

Noget af feedback vi fik:
- Kunne godt lide konceptet med en homescreen med store knapper der hurtigt og nemt tager en der man vil hen
- Ryttere og Heste liste helst sepereret
- Fint med en bottom navigation bar

**Comment by Josef-TL** [comment]
Reflektion af design process: Vi burde have lavet et specifikt design/ detaljeret prototype før vi startede. På dette tidspunkt er alle vores Screens anderledes,+ farver er ikke det samme.

**Comment by Emythiel** [comment]
Implementeret theme baseret på https://material-foundation.github.io/material-theme-builder/

**Comment by Josef-TL** [comment]
Imponerende tidbit: Den kode jeg skrev til flow-collection af firebase data var crangled fra starten af. jeg havde ingen error-handling, så jeg så ikke fejlene. Men da jeg skrev det var der allerede objekter af den korrekte type i firebase, så der var ingen fejl.
